# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install build dependencies and application
COPY pyproject.toml .
COPY src ./src
COPY README.md .

# Install runtime dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential \
    && pip install --no-cache-dir . \
    && apt-get purge -y --auto-remove build-essential \
    && rm -rf /var/lib/apt/lists/*

# Default command
CMD ["python", "-m", "src.opendota_server.server"]
