# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM python:3.11-slim AS build
WORKDIR /app
# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
# Copy project files
COPY pyproject.toml .
COPY src/ src/
# Install Python dependencies
RUN pip install --no-cache-dir .

FROM python:3.11-slim
WORKDIR /app
# Copy installed packages from build
COPY --from=build /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=build /usr/local/bin /usr/local/bin
# Copy application source
COPY src/ src/
# Set environment
ENV PYTHONUNBUFFERED=1
# Default command
CMD ["python", "-m", "src.opendota_server.server"]
